### ISSUE TITLE
[BUG] - Mobile navbar blocking add/edit buttons

### ISSUE THREAD

**Issue by apeskinian** [apeskinian/p4_watch-o-tron#53]
After adding the navbar to the edit and add pages it blocks the cancel and confirm buttons.

![image](https://github.com/user-attachments/assets/61f185ff-649b-4eb7-9c33-6efb32ae11f3)

**Comment by Ilyes-CH** [comment]
Adjust the navbar positioning, If your navbar is set to position: fixed; or position: absolute;, it may overlap with other elements. Try changing its position to static or adjusting the top/bottom margin. In addition, Add padding or margin to the bottom of the content to prevent it from being obscured by the navbar. For example, if your navbar has a height of 60px, you could add padding like 80 px. I also would like to direct your attention to checking the z index and the footer spacing
